In [1]:
import cvimgtest
import numpy as np
import os
import multiprocess as mp
import matplotlib.pyplot as plt
import scipy.io
from PIL import Image


In [68]:
dict_decode={'0':'2','1':'3','2':'4','3':'5','4':'7','5':'9','6':'A','7':'C','8':'F','9':'H','10':'K','11':'M','12':'N'
      ,'13':'P','14':'Q','15':'R','16':'T','17':'Y','18':'Z'}
dict_encode={'2':'0','3':'1','4':'2','5':'3','7':'4','9':'5','A':'6','C':'7','F':'8','H':'9','K':'10','M':'11','N':'12'
      ,'P':'13','Q':'14','R':'15','T':'16','Y':'17','Z':'18'}

In [69]:
def Creat_X_Test():
    path='D:/DLmidterm/owntest/'
    #train
    x_list=[]
#     for i in range(len(os.listdir(path))):
#         arr=cvimgtest.Deal_With_TestImg(i)
#         x_list.append(arr)
    #test
    y=[]
    for i,c in enumerate(os.listdir(path)):
        img=np.array(Image.open(path+c))
        x_list.append(img)
        for num in range(4):
            y.append(int(dict_encode[c[num]]))
    x=np.array([x_list])
    return x,y

In [8]:
def OneHot(data):
    onehotarr=np.uint8(np.zeros((len(data),19)))
    for i,c in enumerate(data):
        onehotarr[i][c]=1
    return onehotarr


In [9]:
def OneHotEncode(data):
    delst=[]
    enlst=np.uint8(np.zeros((1,data.shape[0])))
    for i in range(data.shape[0]):
        d=dict_decode[str(np.argmax(data[i]))]
        enlst[0][i]=str(np.argmax(data[i]))
        delst.append(d)
    return delst,enlst


In [71]:
x,y=Creat_X_Test()
dy=OneHot(y)
_,y=OneHotEncode(dy)

In [72]:
x.shape

(1, 103)

In [73]:
save_fn = 'D:/DLmidterm/owntest.mat'
scipy.io.savemat(save_fn, {'x': x,'y':y,'y_onehot':dy})


In [31]:
enlst=np.uint8(np.zeros((1,dy.shape[0])))
enlst[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [74]:
data=scipy.io.loadmat('D:/DLmidterm/owntest.mat')
x1,y1,y1_onehot=data["x"],data["y"],data["y_onehot"]
data1=scipy.io.loadmat('D:/DLmidterm/train.mat')   
x2,y2,y2_onehot=data1["x"],data1["y"],data1["y_onehot"]

In [189]:
y1

array([[ 8, 15,  9, 13, 13, 10,  0, 12, 15,  6,  3,  6]], dtype=uint8)

In [190]:
y2

array([[ 0,  1,  5, ...,  0,  1, 10]], dtype=uint8)

In [75]:
x

array([[array([[[190, 190, 190],
        [175, 175, 175],
        [231, 231, 231],
        ...,
        [205, 205, 205],
        [189, 189, 189],
        [158, 158, 158]],

       [[194, 194, 194],
        [216, 216, 216],
        [211, 211, 211],
        ...,
        [240, 240, 240],
        [234, 234, 234],
        [234, 234, 234]],

       [[190, 190, 190],
        [163, 163, 163],
        [240, 240, 240],
        ...,
        [182, 182, 182],
        [198, 198, 198],
        [237, 237, 237]],

       ...,

       [[237, 237, 237],
        [192, 192, 192],
        [187, 187, 187],
        ...,
        [208, 208, 208],
        [211, 211, 211],
        [204, 204, 204]],

       [[222, 222, 222],
        [245, 245, 245],
        [211, 211, 211],
        ...,
        [196, 196, 196],
        [209, 209, 209],
        [191, 191, 191]],

       [[225, 225, 225],
        [214, 214, 214],
        [175, 175, 175],
        ...,
        [172, 172, 172],
        [189, 189, 189],
        [199, 19

In [170]:
x
j=np.zeros((3,))


j

array([0., 0., 0.])

In [77]:
x2.shape

(1, 5000)

In [21]:
x2[0]

array([array([[[176, 176, 176],
        [215, 215, 215],
        [239, 239, 239],
        ...,
        [ 52,  52,  52],
        [177, 177, 177],
        [248, 248, 248]],

       [[208, 208, 208],
        [230, 230, 230],
        [182, 182, 182],
        ...,
        [202, 202, 202],
        [192, 192, 192],
        [186, 186, 186]],

       [[211, 211, 211],
        [243, 243, 243],
        [243, 243, 243],
        ...,
        [222, 222, 222],
        [203, 203, 203],
        [186, 186, 186]],

       ...,

       [[193, 193, 193],
        [177, 177, 177],
        [218, 218, 218],
        ...,
        [195, 195, 195],
        [235, 235, 235],
        [216, 216, 216]],

       [[211, 211, 211],
        [199, 199, 199],
        [233, 233, 233],
        ...,
        [212, 212, 212],
        [213, 213, 213],
        [212, 212, 212]],

       [[191, 191, 191],
        [219, 219, 219],
        [185, 185, 185],
        ...,
        [204, 204, 204],
        [175, 175, 175],
        [240, 240

In [43]:
for i in range(5):
    print(x1[0][i].shape)

(48, 133, 3)
(47, 127, 3)
(45, 124, 3)
(46, 115, 3)
(47, 124, 3)


In [293]:
a1=np.array([[2,[2,3]],[4,5]])
a2=np.array([[6,7],[4,8,9],[4,7]])
l=[]
l.append(a1)
l.append(a2)
a=np.array([l])
b=np.array([a])

In [265]:
a[0].shape

(2,)

In [294]:
a1.shape

(2, 2)

In [65]:
a1=np.array(Image.open('D:/DLmidterm/owntest/AZYF.jpg'))
a2=np.array(Image.open('D:/DLmidterm/owntest/T3RC.jpg'))
a3=np.array(Image.open('D:/DLmidterm/owntest/7NY3.jpg'))

In [307]:
a11=np.array([a1])
a22=np.array([a2])

In [14]:

a2.shape

(45, 124, 3)

In [310]:
s=[]
s.append(a11)
s.append(a22)

In [309]:
a11

array([[[[173, 173, 173],
         [185, 185, 185],
         [231, 231, 231],
         ...,
         [203, 203, 203],
         [199, 199, 199],
         [242, 242, 242]],

        [[240, 240, 240],
         [209, 209, 209],
         [212, 212, 212],
         ...,
         [208, 208, 208],
         [176, 176, 176],
         [226, 226, 226]],

        [[236, 236, 236],
         [200, 200, 200],
         [215, 215, 215],
         ...,
         [191, 191, 191],
         [183, 183, 183],
         [214, 214, 214]],

        ...,

        [[225, 225, 225],
         [225, 225, 225],
         [191, 191, 191],
         ...,
         [171, 171, 171],
         [214, 214, 214],
         [216, 216, 216]],

        [[199, 199, 199],
         [234, 234, 234],
         [208, 208, 208],
         ...,
         [236, 236, 236],
         [168, 168, 168],
         [178, 178, 178]],

        [[232, 232, 232],
         [255, 255, 255],
         [216, 216, 216],
         ...,
         [179, 179, 179],
        

In [302]:
s=np.zeros((3,1))
s[0]=a1
s[1]=a2
s


ValueError: could not broadcast input array from shape (2,2) into shape (1)

In [58]:
j1=np.uint8(np.ones((47,127,3)))
j2=np.uint8(np.ones((47,124,3)))
j2.dtype

dtype('uint8')

In [66]:
j=[]
j.append(a1)
j.append(a2)
j.append(a3)
J=np.array([j])
J

array([[array([[[226, 226, 226],
        [180, 180, 180],
        [172, 172, 172],
        ...,
        [232, 232, 232],
        [213, 213, 213],
        [243, 243, 243]],

       [[231, 231, 231],
        [240, 240, 240],
        [255, 255, 255],
        ...,
        [223, 223, 223],
        [164, 164, 164],
        [247, 247, 247]],

       [[183, 183, 183],
        [227, 227, 227],
        [195, 195, 195],
        ...,
        [195, 195, 195],
        [168, 168, 168],
        [179, 179, 179]],

       ...,

       [[184, 184, 184],
        [190, 190, 190],
        [192, 192, 192],
        ...,
        [192, 192, 192],
        [208, 208, 208],
        [248, 248, 248]],

       [[217, 217, 217],
        [229, 229, 229],
        [251, 251, 251],
        ...,
        [191, 191, 191],
        [162, 162, 162],
        [249, 249, 249]],

       [[185, 185, 185],
        [209, 209, 209],
        [189, 189, 189],
        ...,
        [229, 229, 229],
        [179, 179, 179],
        [219, 21

In [63]:
a2.shape

(47, 124, 3)